import {
  BsBackpack,
  BsBasket2,
  BsCodeSlash,
  BsCupHot,
  BsCupStraw,
  BsHouseCheck,
  BsLamp,
  BsLayers,
  BsLungs,
  BsShop,
} from "react-icons/bs";
import { FaDumbbell, FaStar } from "react-icons/fa6";

export const blogData = [
  {
    id: 1,
    image: "/front/temp/blog-2.jpg",
    title: "10 Must-Have Bootstrap Templates for Modern Web Design",
    desc: "Think of a news blog that's filled with content political against opponent Lucius Sergius Catilina. Hourly on the day of going live.",
    date: "13th Sept 2025",
    views: "12k Views",
  },
  {
    id: 2,
    image: "/front/temp/blog-3.jpg",
    title: "Top 5 Bootstrap Themes for E-commerce Websites.",
    desc: "Think of a news blog that's filled with content political against opponent Lucius Sergius Catilina. Hourly on the day of going live.",
    date: "29th Nov 2025",
    views: "33k Views",
  },
  {
    id: 3,
    image: "/front/temp/blog-4.jpg",
    title: "The Ultimate Guide to Customizing Bootstrap Templates",
    desc: "Think of a news blog that's filled with content political against opponent Lucius Sergius Catilina. Hourly on the day of going live.",
    date: "13th March 2025",
    views: "15k Views",
  },
  {
    id: 4,
    image: "/front/temp/blog-5.jpg",
    title: "Top 10 Free Bootstrap Templates for Your Next Project",
    desc: "Think of a news blog that's filled with content political against opponent Lucius Sergius Catilina. Hourly on the day of going live.",
    date: "5th May 2025",
    views: "12k Views",
  },
  {
    id: 5,
    image: "/front/temp/blog-6.jpg",
    title: "Creating Stunning Landing Pages with Bootstrap: Best Practices",
    desc: "Think of a news blog that's filled with content political against opponent Lucius Sergius Catilina. Hourly on the day of going live.",
    date: "19th June 2025",
    views: "33k Views",
  },
  {
    id: 6,
    image: "/front/temp/blog-1.jpg",
    title: "The Benefits of Using Bootstrap for Your Web Development Projects",
    desc: "Think of a news blog that's filled with content political against opponent Lucius Sergius Catilina. Hourly on the day of going live.",
    date: "20th June 2025",
    views: "15k Views",
  },
];

export const categoryData = [
  {
    image: "/front/temp/cats/catt-1.jpg",
    icon: BsBackpack,
    title: "Showroom",
    list: "103 Lists",
  },
  {
    image: "/front/temp/cats/catt-2.jpg",
    icon: BsBasket2,
    title: "Fashion & Beauty",
    list: "110 Lists",
  },
  {
    image: "/front/temp/cats/catt-3.jpg",
    icon: BsHouseCheck,
    title: "Real Estate",
    list: "35 Lists",
  },
  {
    image: "/front/temp/cats/catt-4.jpg",
    icon: FaDumbbell,
    title: "Health & Fitness",
    list: "120 Lists",
  },
  {
    image: "/front/temp/cats/catt-5.jpg",
    icon: BsShop,
    title: "Business Shop",
    list: "69 Lists",
  },
  {
    image: "/front/temp/cats/catt-6.jpg",
    icon: BsCupHot,
    title: "Coffe Shop",
    list: "78 Lists",
  },
  {
    image: "/front/temp/cats/catt-7.jpg",
    icon: BsCupStraw,
    title: "Restaurants",
    list: "69 Lists",
  },
  {
    image: "/front/temp/cats/catt-8.jpg",
    icon: BsLungs,
    title: "Hospital & Med",
    list: "75 Lists",
  },
  {
    image: "/front/temp/cats/catt-9.jpg",
    icon: BsLamp,
    title: "Wedding & Events",
    list: "16 Lists",
  },
  {
    image: "/front/temp/cats/catt-10.jpg",
    icon: BsCupHot,
    title: "Coffe Shop",
    list: "32 Lists",
  },
  {
    image: "/front/temp/cats/catt-9.jpg",
    icon: BsLayers,
    title: "Account Finance",
    list: "16 Lists",
  },
  {
    image: "/front/temp/cats/catt-10.jpg",
    icon: BsCodeSlash,
    title: "Web Development",
    list: "32 Lists",
  },
];

export const reviewData = [
  {
    rate: [FaStar, FaStar, FaStar, FaStar, FaStar],
    title: '"One of the Superb Platform"',
    desc: `Absolutely love Advertize! whenever I'm in need of finding a job, Advertize is my #1 go to! wouldn't look anywhere else.`,
    image: "/front/temp/team-1.jpg",
    name: "Aman Diwakar",
    position: "General Manager",
  },
  {
    rate: [FaStar, FaStar, FaStar, FaStar, FaStar],
    title: '"One of the Superb Platform"',
    desc: `Overall, the Advertize application is a powerful tool for anyone in the job market. Its reliability, extensive job listings, and user-friendly..`,
    image: "/front/temp/team-2.jpg",
    name: "Ridhika K. Sweta",
    position: "CEO of Agreeo",
  },
  {
    rate: [FaStar, FaStar, FaStar, FaStar, FaStar],
    title: '"One of the Superb Platform"',
    desc: `I love this Advertize app. it's more legit than the other ones with advertisement. Once I uploaded my resume, then employers...`,
    image: "/front/temp/team-3.jpg",
    name: "Shushil Kumar Yadav",
    position: "Brand Manager",
  },
  {
    rate: [FaStar, FaStar, FaStar, FaStar, FaStar],
    title: '"One of the Superb Platform"',
    desc: `Advertize the best job finder app out there right now.. they also protect you from spammers so the only emails I get due to...`,
    image: "/front/temp/team-4.jpg",
    name: "Ritika K. Mishra",
    position: "HR Head at Google",
  },
  {
    rate: [FaStar, FaStar, FaStar, FaStar, FaStar],
    title: '"One of the Superb Platform"',
    desc: `Advertize the best job finder app out there right now.. they also protect you from spammers so the only emails I get due to...`,
    image: "/front/temp/team-5.jpg",
    name: "Shree K. Patel",
    position: "Chief Executive",
  },
  {
    rate: [FaStar, FaStar, FaStar, FaStar, FaStar],
    title: '"One of the Superb Platform"',
    desc: `Advertize the best job finder app out there right now.. they also protect you from spammers so the only emails I get due to...`,
    image: "/front/temp/team-6.jpg",
    name: "Sarwan Kumar Patel",
    position: "Chief Executive",
  },
];

export const listData = [
  {
    id: 1,
    image: "/front/temp/list-1.jpg",
    user: "/front/temp/team-1.jpg",
    status: "open",
    featured: true,
    title: "The Big Bumbble Gym",
    desc: "Cicero famously orated against his political.",
    call: "+42 515 635 4758",
    loction: "Tokyo Japan",
    tag: "Fitness",
    tagIcon: FaDumbbell,
    tagIconStyle: "catIcon me-2 cats-1",
    review: "46 Reviews",
    rating: "good",
    ratingRate: "4.5",
    instantBooking: false,
  },
  {
    id: 2,
    image: "/front/temp/list-2.jpg",
    user: "/front/temp/team-2.jpg",
    status: "open",
    featured: false,
    title: "Greenvally Real Estate",
    desc: "Cicero famously orated against his political.",
    call: "+42 515 635 6150",
    loction: "Paris France",
    tag: "Real Estate",
    tagIcon: BsHouseCheck,
    tagIconStyle: "catIcon me-2 cats-2",
    review: "35 Reviews",
    rating: "midium",
    ratingRate: "4.3",
    instantBooking: true,
  },
  {
    id: 3,
    image: "/front/temp/list-3.jpg",
    user: "/front/temp/team-3.jpg",
    status: "closed",
    featured: true,
    title: "Shree Wedding Planner",
    desc: "Cicero famously orated against his political.",
    call: "+42 515 635 4785",
    loction: "Toronto Canada",
    tag: "Weddings",
    tagIcon: BsLamp,
    tagIconStyle: "catIcon me-2 cats-3",
    review: "12 Reviews",
    rating: "excellent",
    ratingRate: "4.8",
    instantBooking: false,
  },
  {
    id: 4,
    image: "/front/temp/list-4.jpg",
    user: "/front/temp/team-4.jpg",
    status: "open",
    featured: false,
    title: "The Blue Ley Light",
    desc: "Cicero famously orated against his political.",
    call: "+42 515 635 6358",
    loction: "Sydney Australia",
    tag: "Restaurant",
    tagIcon: BsCupStraw,
    tagIconStyle: "catIcon me-2 cats-4",
    review: "72 Reviews",
    rating: "good",
    ratingRate: "4.6",
    instantBooking: true,
  },
  {
    id: 5,
    image: "/front/temp/list-5.jpg",
    user: "/front/temp/team-5.jpg",
    status: "close",
    featured: true,
    title: "Shreya Study Center",
    desc: "Cicero famously orated against his political.",
    call: "+42 515 635 0210",
    loction: "Berlin Germany",
    tag: "Education",
    tagIcon: FaDumbbell,
    tagIconStyle: "catIcon me-2 cats-5",
    review: "112 Reviews",
    rating: "midium",
    ratingRate: "4.2",
    instantBooking: false,
  },
  {
    id: 6,
    image: "/front/temp/list-6.jpg",
    user: "/front/temp/team-6.jpg",
    status: "open",
    featured: false,
    title: "Mahroom Garage & Workshop",
    desc: "Cicero famously orated against his political.",
    call: "+42 515 635 3251",
    loction: "Moscow Russia",
    tag: "Showroom",
    tagIcon: BsBackpack,
    tagIconStyle: "catIcon me-2 cats-6",
    review: "52 Reviews",
    rating: "excellent",
    ratingRate: "4.8",
    instantBooking: true,
  },
  {
    id: 7,
    image: "/front/temp/list-7.jpg",
    user: "/front/temp/team-7.jpg",
    status: "open",
    featured: true,
    title: "Creative Wedding Planner",
    desc: "Cicero famously orated against his political.",
    call: "+42 515 635 4758",
    loction: "Rome Italy",
    tag: "Wedding",
    tagIcon: FaDumbbell,
    tagIconStyle: "catIcon me-2 cats-1",
    review: "46 Reviews",
    rating: "good",
    ratingRate: "4.5",
    instantBooking: false,
  },
  {
    id: 8,
    image: "/front/temp/list-8.jpg",
    user: "/front/temp/team-8.jpg",
    status: "close",
    featured: true,
    title: "The Great Dream Palace",
    desc: "Cicero famously orated against his political.",
    call: "+42 515 635 5426",
    loction: "Mumbai India",
    tag: "Spa",
    tagIcon: BsCupHot,
    tagIconStyle: "catIcon me-2 cats-1",
    review: "42 Reviews",
    rating: "excellent",
    ratingRate: "4.9",
    instantBooking: true,
  },
  {
    id: 9,
    image: "/front/temp/list-9.jpg",
    user: "/front/temp/team-9.jpg",
    status: "open",
    featured: true,
    title: "Agroo Spa & Massage Center",
    desc: "Cicero famously orated against his political.",
    call: "+42 515 635 2136",
    loction: "Athens Greece",
    tag: "Eat & Drink ",
    tagIcon: BsBasket2,
    tagIconStyle: "catIcon me-2 cats-8",
    review: "76 Reviews",
    rating: "good",
    ratingRate: "4.7",
    instantBooking: false,
  },
];
